usage: opensource
includes:
- lib
- test
requires:
- sequel
- active_record
- connection_pool
- en57
integration:
  name: minitest
matcher:
  subjects:
    - En57*
  ignore:
    - En57::EventStore.for_active_record
    - En57::EventStore.for_pg
    - En57::EventStore.for_pooled_pg
    - En57::EventStore.for_sequel
    - En57::JsonSerializer#optional_big_decimal_type
    - En57::Migrator*
