name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MUTANT_SINCE: ${{ github.event.pull_request.base.sha || github.event.before }}

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            accept-flake-config = true
            keep-outputs = true
            keep-env-derivations = true
      - name: Cache Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', 'devenv.lock', 'devenv.yaml') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: P1DT12H
          purge-primary-key: never
      - name: Set up cachix
        uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv
        run: nix profile install nixpkgs#devenv
      - name: Cache gems
        uses: actions/cache@v4
        with:
          path: .devenv/state/.bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - name: Run the tests
        run: devenv tasks run test
