name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MUTANT_SINCE: ${{ github.event.pull_request.base.sha || 'HEAD^' }}

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.2'
          bundler-cache: true
      - name: Run the default task
        run: bin/rake
